// Generates firmware/NasaSat/cfg_table.h from tool/src/js/06_cfgdefs.js so that the firmware and the
// web tool always share exactly the same config keys, defaults, ranges and descriptions.
// Usage (from any folder):  node firmware/tools/gen_cfg.js
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', '..');
const js = path.join(root, 'tool', 'src', 'js');
require(path.join(js, '01_util.js'));
require(path.join(js, '06_cfgdefs.js'));
const NS = globalThis.NS;

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const num = (v) => {
  if (!Number.isFinite(v)) throw new Error('non-finite number in cfg defs');
  const s = String(v);
  return /[.eE]/.test(s) ? s : s + '.0';
};
const ids = new Set();
const rows = NS.CFG_DEFS.map((d) => {
  const id = d.k.toUpperCase().replace(/[^A-Z0-9]/g, '_');
  if (ids.has(id)) throw new Error('duplicate id ' + id);
  if (d.k.length > 15) throw new Error('NVS key too long (max 15): ' + d.k);
  ids.add(id);
  return `  X(${id}, "${d.k}", '${d.t}', ${num(d.d)}, ${num(d.min)}, ${num(d.max)}, ${num(d.step)}, "${esc(d.u)}", "${esc(d.g)}", "${esc(d.desc)}")`;
});

const out = `// AUTO-GENERATED by firmware/tools/gen_cfg.js from tool/src/js/06_cfgdefs.js. Do not edit by hand:
// change the JS list, then run  node firmware/tools/gen_cfg.js  so the web tool and firmware stay identical.
#pragma once

// X(ID, key, type, default, min, max, step, unit, group, description)
#define CFG_TABLE(X) \\
${rows.join(' \\\n')}

#define TEL_COLS "${NS.TEL_COLS.join(',')}"
#define M1_STATE_NAMES { ${NS.M1_STATES.map((s) => `"${s}"`).join(', ')} }
`;
const dest = path.join(root, 'firmware', 'NasaSat', 'cfg_table.h');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`wrote ${dest} (${rows.length} keys)`);

// ---- the same list as a readable table for people (and for pasting into an AI chat)
const cell = (s) => String(s).replace(/\|/g, '\|');
const groups = NS.CFG_GROUPS || {};
const md = [
  '# ค่าตั้งทั้งหมดของ NasaSat (สร้างอัตโนมัติ อย่าแก้มือ)',
  '',
  'สร้างจาก `tool/src/js/06_cfgdefs.js` ด้วย `node firmware/tools/gen_cfg.js` (ไฟล์เดียวกับที่ใช้สร้าง `cfg_table.h`)',
  'ตั้งค่าด้วย `SET key value` เก็บถาวรด้วย `SAVE` ค่า i = จำนวนเต็ม, f = ทศนิยม',
  '',
];
let lastG = null;
for (const d of NS.CFG_DEFS) {
  if (d.g !== lastG) {
    md.push('', `## ${groups[d.g] || d.g}`, '', '| key | ชนิด | ค่าเริ่มต้น | ช่วง | หน่วย | ความหมาย |', '|---|---|---|---|---|---|');
    lastG = d.g;
  }
  md.push(`| \`${d.k}\` | ${d.t} | ${d.d} | ${d.min} … ${d.max} | ${cell(d.u)} | ${cell(d.desc)} |`);
}
const mdDest = path.join(root, 'firmware', 'CONFIG_KEYS.md');
fs.writeFileSync(mdDest, md.join('\n') + '\n');
console.log(`wrote ${mdDest}`);
